name: mobile_scanner
description: A universal scanner for Flutter based on MLKit. Uses CameraX on Android and AVFoundation on iOS.
version: 0.1.0
repository: https://github.com/juliansteenbakker/mobile_scanner

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  js: ^0.6.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.mobile_scanner
        pluginClass: MobileScannerPlugin
      ios:
        pluginClass: MobileScannerPlugin
      macos:
        pluginClass: MobileScannerPlugin